apiVersion: plugin.halo.run/v1alpha1
kind: Plugin
metadata:
  name: PluginTuiEditor
spec:
  enabled: true
  version: 1.0.0-SNAPSHOT
  requires: "*"
  author:
    name: Halo OSS Team
    website: https://github.com/halo-dev
  logo: https://halo.run/logo
  settingName: plugin-tui-editor-settings
  configMapName: plugin-tui-editor-configMap
  homepage: https://github.com/halo-dev/plugin-tui.editor
  displayName: "tui.editor"
  description: "对 tui.editor 的集成，让文章支持 Markdown 编辑"
  license:
    - name: "MIT"
